### ISSUE TITLE
Test GetActualArea fix

### ISSUE THREAD

**Issue by lukaszkrzywizna** [domn1995/dunet#45]
Hi,

Currently, the test `CanReturnImplementationsOfGenericUnion` use default implementation of `ToString` method for a double. This can cause errors when users have different culture-info settings.

```csharp
Xunit.Sdk.XunitException
Expected actualArea to be "0.5", but "0,5" differs near ",5" (index 1).
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstMismatch()
   at FluentAssertions.Primitives.StringValidator.Validate()
   at FluentAssertions.Primitives.StringAssertions`1.Be(String expected, String because, Object[] becauseArgs)
   at Dunet.Test.GenerateUnionRecord.GenericGenerationTests.CanReturnImplementationsOfGenericUnion(Int32 dividend, Int32 divisor, String expectedOutput) in C:\repos\external-repo\dunet\test\GenerateUnionRecord\GenericGenerationTests.cs:line 104

```

The suggested fix is to add `InvariantCulture` parameter.

Note: Creating pull requests is blocked so I present the solution below:
![image](https://user-images.githubusercontent.com/12534253/179476469-72cbe590-4f85-4bb2-a918-59a98064aaee.png)

**Comment by domn1995** [comment]
Thanks for the suggestion. I'm not aware of anything blocking pull requests. What error are you seeing?

**Comment by lukaszkrzywizna** [comment]
![image](https://user-images.githubusercontent.com/12534253/179534547-f2f40a90-e13b-4919-9aab-e01ab8fdc95c.png)
Based on official documentation only collaborators can create pull requests. https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github#personal-accounts

**Comment by domn1995** [comment]
I don't see a fork of the repo under your account. Are you trying to push directly to this repo before opening your PR? That might be the problem. I believe if you fork the repo you should be able to PR the fork just fine.

**Comment by domn1995** [comment]
Just merged a fix for this. Let me know if you are unable to submit pull requests with a forked repo and I'll take another look at the permissions.

**Comment by lukaszkrzywizna** [comment]
I didn't know about the option with the forked repo. It works like a charm. Thanks! :)
